import React from "react";
import { AppPreferencesProvider } from "../components/AppPreferencesProvider";
import "./globals.css";

export const metadata = {
  title: "EcardHub",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/logo/icon-gold-navy.svg", type: "image/svg+xml" },
      { url: "/logo/ecardhub-icon-gold-navy-192.png", sizes: "192x192", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: "/favicon.ico",
    apple: [
      { url: "/apple-touch-icon.png", sizes: "512x512", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <AppPreferencesProvider>{children}</AppPreferencesProvider>
      </body>
    </html>
  );
}
