import type { Category, Template } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "graduation",
    emoji: "🎓",
    label: "Graduation",
    labelSw: "Uhitimu",
    color: "#11131F",
    accent: "#E0B863",
  },
  {
    id: "wedding",
    emoji: "💍",
    label: "Wedding",
    labelSw: "Harusi",
    color: "#4C2456",
    accent: "#E5C158",
  },
  {
    id: "birthday",
    emoji: "🎂",
    label: "Birthday",
    labelSw: "Siku ya Kuzaliwa",
    color: "#1E3A2F",
    accent: "#F9C74F",
  },
  {
    id: "babyshower",
    emoji: "👶",
    label: "Baby Shower",
    labelSw: "Sherehe ya Mtoto",
    color: "#1A3045",
    accent: "#A8D8EA",
  },
  {
    id: "anniversary",
    emoji: "🎉",
    label: "Anniversary",
    labelSw: "Kumbukumbu",
    color: "#3D1C1C",
    accent: "#E8956D",
  },
  {
    id: "religious",
    emoji: "🕌",
    label: "Religious",
    labelSw: "Kidini",
    color: "#1B2E1B",
    accent: "#8FBE8F",
  },
  {
    id: "corporate",
    emoji: "🏢",
    label: "Corporate",
    labelSw: "Kampuni",
    color: "#1A1F35",
    accent: "#90CAF9",
  },
  {
    id: "holiday",
    emoji: "🎄",
    label: "Holiday",
    labelSw: "Likizo",
    color: "#1C2B1C",
    accent: "#D4E8A0",
  },
  {
    id: "thankyou",
    emoji: "💌",
    label: "Thank You",
    labelSw: "Asante",
    color: "#2E1A2E",
    accent: "#F4A6C2",
  },
  {
    id: "memorial",
    emoji: "😢",
    label: "Memorial",
    labelSw: "Ukumbusho",
    color: "#1F1F2E",
    accent: "#B0B8D4",
  },
];

export const TEMPLATES: Template[] = [
  {
    id: "t1",
    categoryId: "wedding",
    title: "Eternal Bond",
    subtitle: "A timeless wedding invitation",
    bgGradient: "linear-gradient(135deg, #4C2456 0%, #2D1235 100%)",
    textColor: "#FFFFFF",
    accentColor: "#E5C158",
    uses: 12840,
    premium: false,
  },
  {
    id: "t2",
    categoryId: "graduation",
    title: "Golden Milestone",
    subtitle: "Celebrate academic excellence",
    bgGradient: "linear-gradient(135deg, #11131F 0%, #25283D 100%)",
    textColor: "#FFFFFF",
    accentColor: "#E0B863",
    uses: 8920,
    premium: false,
  },
  {
    id: "t3",
    categoryId: "birthday",
    title: "Joyful Celebration",
    subtitle: "Make their day unforgettable",
    bgGradient: "linear-gradient(135deg, #1E3A2F 0%, #2D5A44 100%)",
    textColor: "#F0FFF4",
    accentColor: "#F9C74F",
    uses: 24100,
    premium: false,
  },
  {
    id: "t4",
    categoryId: "babyshower",
    title: "Little Wonder",
    subtitle: "Welcome a new precious life",
    bgGradient: "linear-gradient(135deg, #1A3045 0%, #2A4D6E 100%)",
    textColor: "#EFF8FF",
    accentColor: "#A8D8EA",
    uses: 7340,
    premium: true,
  },
  {
    id: "t5",
    categoryId: "anniversary",
    title: "Years of Love",
    subtitle: "Honor a remarkable journey",
    bgGradient: "linear-gradient(135deg, #3D1C1C 0%, #5E2E2E 100%)",
    textColor: "#FFF5F0",
    accentColor: "#E8956D",
    uses: 5620,
    premium: true,
  },
  {
    id: "t6",
    categoryId: "corporate",
    title: "Professional Gather",
    subtitle: "Corporate event elegance",
    bgGradient: "linear-gradient(135deg, #1A1F35 0%, #252D50 100%)",
    textColor: "#F0F4FF",
    accentColor: "#90CAF9",
    uses: 9810,
    premium: false,
  },
  {
    id: "t7",
    categoryId: "holiday",
    title: "Season's Warmth",
    subtitle: "Holiday greetings with heart",
    bgGradient: "linear-gradient(135deg, #1C2B1C 0%, #2A422A 100%)",
    textColor: "#F4FFF4",
    accentColor: "#D4E8A0",
    uses: 31200,
    premium: false,
  },
  {
    id: "t8",
    categoryId: "memorial",
    title: "In Loving Memory",
    subtitle: "Honor those we hold dear",
    bgGradient: "linear-gradient(135deg, #1F1F2E 0%, #2E2E42 100%)",
    textColor: "#F0F0F8",
    accentColor: "#B0B8D4",
    uses: 3200,
    premium: false,
  },
  {
    id: "t9",
    categoryId: "thankyou",
    title: "Heartfelt Thanks",
    subtitle: "Express genuine gratitude",
    bgGradient: "linear-gradient(135deg, #2E1A2E 0%, #4A2A4A 100%)",
    textColor: "#FFF0F8",
    accentColor: "#F4A6C2",
    uses: 15600,
    premium: false,
  },
  {
    id: "t10",
    categoryId: "religious",
    title: "Sacred Blessing",
    subtitle: "A spiritual celebration",
    bgGradient: "linear-gradient(135deg, #1B2E1B 0%, #284328 100%)",
    textColor: "#F4FFF4",
    accentColor: "#8FBE8F",
    uses: 6700,
    premium: true,
  },
];
