# Generated by Django 6.1 on 2026-08-19 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('graduation', 'Graduation'), ('birthday', 'Birthday'), ('kitchen_party', 'Kitchen Party'), ('holiday', 'Holiday'), ('anniversary', 'Anniversary'), ('send_off', 'Send-off'), ('custom_ceremony', 'Custom Ceremony')], max_length=30)),
                ('host_family_name', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=255)),
                ('rsvp_deadline', models.DateField(blank=True, null=True)),
                ('rsvp_reply_phone', models.CharField(blank=True, max_length=20)),
                ('card_message', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
