# Generated by Django 6.1 on 2026-08-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dress_code_colors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
